server:
  port: "5005"

db:
  port: 3306
  host: "localhost"
  dbName: "insight"
  username: "root"

job:
  passJobTime: 10

mail:
  host: "smtp.gmail.com"
  port: 465
  username: ""
  password: ""
  address: ""

